on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          ng deploy
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

