on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npx ng deploy --cname=aidenschrock.me
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

